name: SpectralOps
on: [push]
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Preflight
        uses: SpectralOps/setup-preflight-action@v1
      - name: Spectral Install
        run: curl -L "https://get.spectralops.io/latest/sh?dsn=$SPECTRAL_DSN" | preflight run sha256=1981831d4707f9421dacbe185d88a460dec55d4976b99d369d3b884d6336b62d
      - name: Spectral Scan
        run: spectral scan
